# 📌4.1 사라진 SQLException
JdbcTemplate에 있는 메소드들은 SQLException을 던지지 않는다.

그렇다면 이 SQLException은 어디로 간 것일까?
## 4.1.1 초난감 예외처리
**✔ 예외블랙홀**

개발자들의 코드에서 종종 발견되는 초난감 예외처리의 경우들을 살펴보자.
```JAVA
try {
  ...
} catch (SQLException e) { 
}
```
> 예외를 잡고는 아무것도 하지 않는 경우다. 예외 발생을 무시해버리고 정상적인 상황인 것처럼 다음 라인으로 넘어가겠다는 분명한 의도가 있는 게 아니라면 연습 중에도 절대 만들어서는 안 되는 코드다. 왜냐하면 프로그램 실행 중에 어디선가 오류가 있어서 예외가 발생했는데 그것을 무시하고 계속 진행해버리기 때문이다.
>
> 위와 같은 예외 처리 때문에 프로그램이 오작동을 하거나 시스템 오류가 나서 운영자가 알아차렸을 때는 이미 조치를 취하기엔 너무 늦었다. 더 큰 문제는 그 시스템 오류나 이상한 결과의 원인이 무엇인지 찾아내기가 매우 힘들다는 점이다.


**✔ 단순 예외 출력**
```JAVA
} catch (SQLException e) { 
    System.out.println(e);
}
```
```JAVA
} catch (SQLException e) { 
    e.printStackTrace();
}
```
> 예외는 처리되어야 한다. 화면에 메시지를 출력한 것은 예외를 처리한 게 아니다.
>
> 예외를 처리할 때 개발자가 반드시 지켜야 할 핵심 원칙은 한 가지다. 모든 예외는 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다.

**✔ 무의미하고 무책임한 throws**

catch 블록으로 예외를 잡아봐야 해결할 방법도 없고, 각종 API나 라이브러리가 던지는 긴 이름의 예외들을 매번 throws로 던지기도 귀찮아지면, 다음과 같이 모든 메소드에 throws Exception을 기계적으로 붙이는 개발자도 있다.
```JAVA
public void method1() throws Exception {
    method2();
    ...
}
```
```JAVA
public void method2() throws Exception {
    method3();
    ...
}
```
```JAVA
public void method3() throws Exception {
    ...
}
```
> 자신이 사용하려고 하는 메소드에 throws Exception이 선언되어 있다고 생각해보자. 그런 메소드 선언에서는 의미 있는 정보를 얻을 수 없다. 정말 무엇인가 실행 중에 예외적인 상황이 발생할 수 있다는 것인지, 아니면 그냥 습관적으로 복사해서 붙여 놓은 것인지 알 수가 없다. 결국 이런 메소드를 사용하는 메소드에서도 역시 throws Exception을 따라서 붙이는 수밖에 없다. 결과적으로 적절한 처리를 통해 복구될 수 있는 예외상황도 제대로 다룰 수 있는 기회를 박탈당한다.
## 4.1.2 예외의 종류와 특징
자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세 가지가 있다.

**✔ Error**
> 첫째는 java.lang.Error 클래스의 서브클래스들이다. 에러는 시스템에 뭔가 비정상적인 상황이 발생했을 경우에 사용된다. 그래서 주로 자바 VM에서 발생시키는 것이고 애플리케이션 코드에서 잡으려고 하면 안 된다. 따라서 시스템 레벨에서 특별한 작업을 하는 게 아니라면 애플리케이션에서는 이런 에러에 대한 처리는 신경 쓰지 않아도 된다.

**✔ Exception과 체크 예외**
>java.lang.Exception 클래스와 그 서브클래스로 정의되는 예외들은 에러와 달리 개발자들이 만든 애플리케이션 코드의 작업 중에 예외상황이 발생했을 경우에 사용된다.
>
>Exception 클래스는 다시 체크 예외(Checked Exception) 와 언체크 예외(Unchecked Exception) 로 구분된다. 전자는 Exception 클래스의 서브클래스이면서 RuntimeException 클래스를 상속하지 않은 것들이고, 후자는 RuntimeException을 상속한 클래스들을 말한다.
>
>일반적으로 예외라고 하면 Exception 클래스의 서브클래스 중에서 RuntimeException을 상속하지 않은 것만을 말하는 체크 예외라고 생각해도 된다. 체크 예외가 발생할 수 있는 메소드를 사용할 경우 반드시 예외를 처리하는 코드를 함께 작성해야 한다.

**✔ RuntimeException과 언체크/런타임 예외**
> java.lang.RuntimeException 클래스를 상속한 예외들은 명시적인 예외처리를 강제하지 않기 때문에 언체크 예외라고 불린다. 또는 대표 클래스 이름을 따서 런타임 예외라고도 한다. 에러와 마찬가지로 이 런타임 예외는 catch문으로 잡거나 throws로 선언하지 않아도 된다.
>
> 런타임 예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도된 것들이다. 이런 예외는 코드에서 미리 조건을 체크하도록 주의 깊게 만든다면 피할 수 있다. 피할 수 있지만 개발자가 부주의해서 발생할 수 있는 경우에 발생하도록 만든 것이 런타임 예외다.

## 4.1.3 예외 처리 방법
먼저 예외를 처리하는 일반적인 방법을 살펴보고 나서 효과적인 예외처리 전략을 생각해 보자.

**✔ 예외복구**
```JAVA
int maxretry = MAX_RETRY; 
while(maxretry — > 0) {
    try {
        ... // 예외가 발생할 가능성이 있는 시도
        return;
    }
    catch(SomeException e) {
        // 로그 출력. 정해진 시간만큼 대기
    } finally {
        // 리소스 반납. 정리 작업
    } 
}
throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외 발생
```
> 첫 번째 예외처리 방법은 예외상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것이다. 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도해주는 것이다. 예외처리 코드를 강제하는 체크 예외들은 이렇게 예외를 어떤 식으로든 복구할 가능성이 있는 경우에 사용한다.

**✔ 예외처리 회피**
```JAVA
try {
  ...
} catch (SQLException e) {
    throw e;
}
```
> 두 번째 방법은 예외처리를 자신이 담당하지 않고 자신을 호출한 쪽으로 던져버리는 것이다. throws 문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch 문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는 것이다.
>
> 하지만 콜백과 템플릿처럼 긴밀하게 역할을 분담하고 있는 관계가 아니라면 자신의 코드에서 발생하는 예외를 그냥 던져버리는 건 무책임한 책임회피일 수 있다. 예외를 회피하는 것은 예외를 복구하는 것처럼 의도가 분명해야 한다. 템플릿/콜백처럼 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야 한다.

**✔ 예외 전환**
```JAVA
....
} catch (SQLException e) {
    throw DuplicateUserIdException(e);
}

```
> 마지막으로 예외를 처리하는 방법은 예외 전환(Exception Translation)을 하는 것이다. 예외 회피와 비슷하게 예외를 복구해서 정상적인 상태로는 만들 수 없기 때문에 예외를 메소드 밖으로 던지는 것이다. 하지만 예외 회피와 달리, 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다는 특징이 있다.
> 
> 예외 전환은 보통 두 가지 목적으로 사용된다.
>
>> 첫 번째는 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적절한 의미를 부여해주지 못하는 경우에, 의미를 분명하게 해줄 수 있는 예외로 바꿔주기 위해서다. 상황에 적합한 의미를 가진 예외로 변경하는 것이다. 보통 전환하는 예외에 원래 발생한 예외를 담아서 중첩 예외(Nested Exception)로 만드는 것이 좋다.
>>
>> 두 번째 전환방법은 예외를 처리하기 쉽고 단순하게 만들기 위해 포장(wrap)하는 것이다. 주로 예외처리를 강제하는 체크 예외를 언체크 예외인 런타임 예외로 바꾸는 경우에 사용한다.

## 4.1.4 예외 처리 전략
예외의 종류와 처리 방법 등을 기준으로 일관된 예외처리 전략을 정리해 보자.

**✔ 런타임 예외의 보편화**
```JAVA
public class DuplicateUserException extends RuntimeException {
    public DuplicateUserException(Throwable cause) {
      super(cause);
    }
}
public void add() throws DuplicateUserException {
    try {
    } catch (SQLException e) {
        if (e.getErrorCode() == ERR_DUP_ENTRY) {
            throw new DuplicateUserException(e);
        } else {
            throw new RuntimeException(e);
        }
    } 
}
```
> 일반적으로는 체크 예외가 일반적인 예외를 다루고, 언체크 예외는 시스템 장애나 프로그램상의 오류에 사용한다고 했다. 문제는 체크 예외는 복구할 가능성이 조금이라도 있는, 말 그대로 예외적인 상황이기 때문에 자바는 이를 처리하는 catch 블록이나 throws 선언을 강제하고 있다는 점이다. 이렇게 예외처리를 강제하는 것은 예외가 발생할 가능성이 있는 API 메소드를 사용하는 개발자의 실수를 방지하기 위한 배려라고 볼 수도 있겠지만, 실제로는 예외를 다루고 싶지 않을 만큼 짜증나게 만드는 원인이 되기도 한다.
>
> 자바가 처음 만들어질 때 사용되던 독립형 어플리케이션에서는 통제 불가능한 시스템 예외라고 할지라도 애플리케이션의 작업이 중단되지 않게 해주고 상황을 복구해야 했다. 예를 들어 워드의 파일 열기 기능에서 사용자가 입력한 이름에 해당하는 파일을 찾을 수 없다고 애플리케이션이 종료돼버리게 할 수는 없다.
>
> 하지만 자바 엔터프라이즈 서버환경은 다르다. 수많은 사용자가 동시에 요청을 보내고 각 요청이 독립적인 작업으로 취급된다. 하나의 요청을 처리하는 중에 예외가 발생하면 해당 작업만 중단시키면 그만이다. 독립형 애플리케이션과 달리 서버의 특정 계층에서 예외가 발생했을 때 작업을 일시 중지하고 사용자와 바로 커뮤니케이션하면서 예외상황을 복구할 수 있는 방법이 없다.
>
> 차라리 애플리케이션 차원에서 예외상황을 미리 파악하고, 예외가 발생하지 않도록 차단하는 게 좋다. 자바의 환경이 서버로 이동하면서 체크 예외의 활용도와 가치는 점점 떨어지고 있다. 최근에 등장하는 표준 스펙 또는 오픈소스 프레임워크에서는 API가 발생시키는 예외를 체크 예외 대신 언체크 예외로 정의하는 것이 일반화되고 있다.

**✔ 애플리케이션 예외**
```JAVA
try {
  BigDecimal balance = account.withdraw(amount);
  ...
  // 정상적인 처리 로직 수행
} catch (InsufficientBalanceException e) {
  // InsufficientBalanceException 의 인출가능한 잔고금액 정보를 가지고 옴
  BigDecimal avaliFunds = e.getAvailFunds();
  ...
  // 잔고부족 메세지 출력
}
```
> 런타임 예외 중심의 전략은 굳이 이름을 붙이자면 낙관적인 예외처리 기법이라고 할 수 있다. 일단 잡고 보도록 강제하는 체크 예외의 비관적인 접근 방법과 대비된다.
>
> 반면에 시스템 또는 외부의 예외상황이 원인이 아니라 애플리케이션 자체의 로직에 의해 의도적으로 발생시키고, 반드시 catch 해서 무엇인가 조치를 취하도록 요구하는 예외도 있다. 이런 예외들을 일반적으로 애플리케이션 예외라고 한다. 은행계좌에서 돈을 출금하는 시점에서 잔고 부족 등의 예외 상황이 발생할 경우, 이를 특정한 리턴 값이나 if문으로 모든 상황을 분기처리해서 나눌 필요 없이, InsufficientBalanceException 등의 예외를 던지도록 만들 수 있다. 이때 사용하는 예외는 의도적으로 체크 예외로 만든다. 그래서 개발자가 잊지 않고 잔고 부족처럼 자주 발생 가능한 예외상황에 대한 로직을 구현하도록 강제해주는 게 좋다.

## 4.1.5 SQLException은 어떻게 됐나?
SQLException은 과연 복구가 가능한 예외인가이다. 99%의 SQLException은 코드 레벨에서는 복구할 방법이 없다.

시스템의 예외라면 당연히 애플리케이션 레벨에서 복구할 방법이 없다. 관리자나 개발자에게 빨리 예외가 발생했다는 사실이 알려지도록 전달하는 방법밖에는 없다.

대부분의 SQLException은 복구가 불가능하다. 더군다나 DAO 밖에서 SQLException을 다룰 수 있는 가능성은 거의 없다. 따라서 예외처리 전략을 적용해야 한다. 필요도 없는 기계적인 throws 선언이 등장하도록 방치하지 말고 가능한 한 빨리 언체크/런타임 예외로 전환해줘야 한다.

스프링의 JdbcTemplate은 바로 이 예외처리 전략을 따르고 있다. JdbcTemplate 템플릿과 콜백 안에서 발생하는 모든 SQLException을 런타임 예외인 DataAccessException으로 포장해서 던져준다.
# 📌4.2 예외 전환
**DataAccessException**
- 예외를 다른 것으로 바꿔서 던지는 예외 전환의 목적은 두 가지라고 설명했다. 하나는 앞에서 적용해본 것처럼 런타임 예외로 포장해서 굳이 필요하지 않은 catch/throws를 줄여주는 것이고, 다른 하나는 로우레벨의 예외를 좀 더 의미 있고 추상화된 예외로 바꿔서 던져주는 것이다.
- 스프링의 JdbcTemplate이 던지는 DataAccessException은 일단 런타임 예외로 SQLException을 포장해주는 역할을 한다. 그래서 대부분 복구가 불가능한 예외인 SQLException에 대해 애플리케이션 레벨에서는 신경 쓰지 않도록 해주는 것이다. 또한 DataAccessException은 SQLException에 담긴 다루기 힘든 상세한 예외정보를 의미 있고 일관성 있는 예외로 전환해서 추상화해주려는 용도로 쓰이기도 한다.
## 4.2.1 JDBC의 한계
JDBC는 자바를 이용해 DB에 접근하는 방법을 추상화된 API 형태로 정의해놓고, 각 DB 업체가 JDBC 표준을 따라 만들어진 드라이버를 제공하게 해준다. 내부 구현은 DB마다 다르겠지만 JDBC의 Connection. Statement. ResultSet 등의 표준 인터페이스를 통해 그 기능을 제공해주기 때문에 자바 개발자들은 표준화된 JDBC의 API에만 익숙해지면 DB의 종류에 상관없이 일관된 방법으로 프로그램을 개발할 수 있다.

표준화된 JDBC API가 DB 프로그램 개발 방법을 학습하는 부담은 확실히 줄여주지만 DB를 자유롭게 변경해서 사용할 수 있는 유연한 코드를 보장해주지는 못한다. 현실적으로 DB를 자유롭게 바꾸어 사용할 수 있는 DB 프로그램을 작성하는데는 **두가지** 걸림돌이 있다.

**✔ 비표준 SQL**
> 대부분의 DB는 표준을 따르지 않는 비표준문법과 기능도 제공한다. 이런 비표준 특정 DB 전용 문법은 매우 폭넓게 사용되고 있다.
> 
> 이 문제의 해결책을 생각해보면, 호환 가능한 표준 SQL만 사용하는 방법과 DB별로 별도의 DAO를 만들거나 SQL을 외부에 독립시켜서 DB에 따라 변경해 사용하는 방법이 있다.

**✔ 호환성 없는 SQLException의 DB 에러정보**
> DB마다 에러의 종류와 원인도 제각각이다.
> JDBC는 데이터 처리 중에 발생하는 다양한 예외를 그냥 SQLException 하나에 모두 담아버린다. JDBC API는 이 SQLException 한 가지만 던지도록 설계되어 있다. 예외가 발생한 원인은 SQLException 안에 담긴 에러 코드와 SQL 상태정보를 참조해봐야 한다.
> SQLException의 getErrorCode()로 가져올 수 있는 DB 에러 코드는 DB별로 모두 다르다. DB 벤더가 정의한 고유한 에러 코드를 사용하기 때문이다.
> SQLException은 예외가 발생했을 때의 DB 상태를 담은 SQL 상태정보를 부가적으로 제공한다. getSQLState() 메소드로 예외상황 대한 상태정보를 가져올 수 있다.
> SQLException이 이러한 상태 코드를 제공하는 이유는 DB에 독립적인 에러정보를 얻기 위해서다. 그런데 문제는 DB의 JDBC 드라이버에서 SQLException이 담을 상태 코드를 정확하게 만들어주지 않는다는 점이다.
> 결국 호환성 없는 에러 코드와 표준을 잘 따르지 않는 상태 코드를 가진 SQLException만으로 DB에 독립적인 유연한 코드를 작성하는 건 불가능에 기깝다.

## 4.2.2 DB 에러 코드 매핑을 통한 전환
해결 방법은 DB별 에러 코드를 참고해서 발생한 예외의 원인이 무엇인지 해석해주는 기능을 만드는 것이다.

스프링은 DataAccessException이라는 SQLException을 대체할 수 있는 런타임 예외를 정의하고 있을 뿐 아니라 DataAccessException의 서브클래스로 세분화된 예외 클래스들을 정의하고 있다.

스프링은 DB별 에러 코드를 분류해서 스프링이 정의한 예외 클래스와 매핑해놓은 에러 코드 매핑정보 테이블을 만들어두고 이를 이용한다.
```XML
<bean id="Oracle" class="org.springframework.jdbc.support.SQLErrorCodes">
		<property name="badSqlGrammarCodes">
			<value>900,903,904,917,936,942,17006,6550</value>
		</property>
		<property name="invalidResultSetAccessCodes">
			<value>17003</value>
		</property>
		<property name="duplicateKeyCodes">
			<value>1</value>
		</property>
		<property name="dataIntegrityViolationCodes">
			<value>1400,1722,2291,2292</value>
		</property>
		<property name="dataAccessResourceFailureCodes">
			<value>17002,17447</value>
		</property>
		<property name="cannotAcquireLockCodes">
			<value>54,30006</value>
		</property>
		<property name="cannotSerializeTransactionCodes">
			<value>8177</value>
		</property>
		<property name="deadlockLoserCodes">
			<value>60</value>
		</property>
</bean>
```

JdbcTemplate은 SQLException을 단지 런타임 예외인 DataAccessException으로 포장하는 것이 아니라 DB의 에러 코드를 DataAccessException 계층구조의 클래스 중 하나로 매핑해준다.

또, DB 종류와 상관없이 중복키로 발생되는 예외는 DataAcessException의 서브 클래스인 DuplicateKeyException으로 매핑돼서 던져진다. add() 메소드를 사용하는 쪽에서 중복 키 상황에 대한 대응이 필요한 경우 참고할 수 있도록 아래와 같이 DuplicateKeyException을 메소드 선언에 넣어주면 편리하다.
```JAVA
    public void add(User user) throws DuplicateUserIdException {
        try {
            this.jdbcTemplate.update("insert into users(id, name, password) values (?, ?, ?)"
                    , user.getId()
                    , user.getName()
                    , user.getPassword()
            );
        } catch (DuplicateKeyException e) {
            throw new DuplicateUserIdException(e);
        }
    }
```
> 위와 같이 add() 메소드를 작성하게 되면, JdbcTemplate은 SQLException 대신에 DataAcessException 계층구조의 예외로 포장해주기 때문에, add() 메소드에 예외 포장을 위한 코드가 따로 필요 없다.

JdbcTemplate에서 던지는 예외는 모두 DataAccessException의 서브클래스 타입이다. 드라이버나 DB 메타정보를 참고해서 DB 종류를 확인하고 DB별로 미리 준비된 매핑정보를 참고해서 적절한 예외 클래스를 선택하기 때문에 DB가 달라져도 같은 종류의 에러라면 동일한 예외를 받을 수 있는 것이다.

JDK 1.6에 포함된 JDBC 4.0부터는 기존에 JDBC의 단일 예외 클래스였던 SQLException을 스프링의 DataAccessException과 비슷한 방식으로 좀 더 세분화해서 정의하고 있다.

## 4.2.3 DAO 인터페이스와 DataAccessException 계층구조
DataAccessException은 의미가 같은 예외라면 데이터 액세스 기술의 종류와 상관없이 일관된 예외가 발생하도록 만들어준다. 데이터 액세스 기술에 독립적인 추상화된 예외를 제공하는 것이다.

스프링이 왜 이렇게 DataAccessException 계층구조를 이용해 기술에 독립적인 예외를 정의하고 사용하게 하는지 생각해보자.

**✔ DAO 인터페이스와 구현 분리**

UserDao의 add() 메소드는 어떤 데이터 액세스 기술을 사용하느냐에 따라서 throw 하는 예외가 달라진다. 데이터 액세스 기술에 따라 발생하는 예외가 전부 다르기 때문이다.
```JAVA
public void add(User user) throws PersistentException; // JPA
public void add(User user) throws HibernateException;  // Hibernate
public void add(User user) throws JdoException; // JDO
```
> 결국 인터페이스로 메소드의 구현은 추상화했지만 구현 기술마다 던지는 예외가 다르기 때문에 메소드의 선언이 달라진다는 문제가 발생한다. DAO 인터페이스를 기술에 완전히 독립적으로 만들려면 예외가 일치하지 않는 문제도 해결해야 한다.
>
> 가장 단순한 해결 방법은 모든 예외를 다 받아주는 throws Exception으로 선언하는것이다. 하지만 무책임한 선언이다.
>
> 데이터 액세스 기술이 달라지면 같은 상황에서도 다른 종류의 예외가 던져진다. 따라서 DAO를 사용하는 클라이언트 입장에서는 DAO의 사용 기술에 따라서 예외 처리 방법이 달라져야한다.
>
> 인터페이스로 추상화하고 일부 기술에서 발생하는 체크 예외를 런타임 예외로 전환하는 것만으론 불충분하다.

**✔ 데이터 액세스 예외 추상화와 DataAccessException 구조**

스프링의 JdbcTemplate은 SQLException의 에러 코드를 DB 별로 매핑해서 그에 해당하는 의미 있는 DataAccessException의 서브클래스 중 하나로 전환해서 던져준다.

DataAccessException은 자바의 주요 데이터 액세스 기술에서 발생할 수 있는 대부분의 예외를 추상화하고 있다.

DataAccessException 계층구조에는 템플릿 메소드나 DAO 메소드에서 직접 활용할 수 있는 예외도 정의되어 있다.

## 4.2.4 기술에 독립적은 UserDao 만들기

**✔ 인터페이스 적용**

인터페이스 이름 앞에는 I라는 접두어를 붙이는 방법도 있고, 인터페이스 이름을 기본형으로 가장 단순하게 하고 구현 클래스는 각각의 특징을 따르는 이름을 붙이는 경우도 있다. 여기서는 후자의 방법을 사용한다. 우리가 만드는 인터페이스 이름은 UserDao로 하고, 현재 만들어놨던 구현체는 UserDaoJdbc라고 해보자.
```JAVA
public interface UserDao {
    void add(User user);
    User get(String id);
    User getByName(String name);
    List<User> getAll();
    void deleteAll();
    int getCount();
}
```
```JAVA
public class UserDaoJdbc implements UserDao {
```

> 위와 같이 인터페이스를 추가하고 UserDaoJdbc가 UserDao를 상속하도록 했다. getByName()은 queryForObject()의 결과가 2건 이상일 때를 테스트하기 위해서 이름으로 검색하는 부분을 만들어보았다.
>
> 또, setDataSource() 메소드는 인터페이스에 추가하면 안된다는 사실에 주의하자. setDataSource()메소드는 UserDao의 구현 방법에 따라 변경될 수 있는 메소드이고, UserDao를 사용하는 클라이언트가 알고 있을 필요도 없다.

```XML
<bean id="userDao" class="toby_spring.user.dao.UserDaoJdbc">
        <property name="jdbcTemplate" ref="jdbcTemplate" />
</bean>
```
> 스프링 설정파일도 변경해 준다.
>
> 구현체는 UserDaoJdbc라는 클래스를 그대로 사용해주고, 빈의 id는 관례상 인터페이스의 이름으로 해주었다. 그래야 나중에 인터페이스를 마음껏 바꾸어도 혼란이 없다.

**✔ 테스트 보완**

UserDaoJdbc라는 구현체 자체를 테스트하고 싶다면, 명확하게 UserDaoJdbc 타입을 받아오는 편이 좋지만, UserDao를 테스트하고자 한다면, UserDao 타입을 이용해서 UserDaoJdbc 타입의 빈을 주입받는 것이 더 옳다.

중복된 유저를 등록하는 테스트를 추가해 보자.
```JAVA
@Test(expected=DataAccessException.class)
    public void addDuplicateUsers() {
        dao.deleteAll();
        
        dao.add(user1);
        dao.add(user2);
    }
```
> 스프링의 JdbcTemplate을 사용해서 등록하기 때문에, 스프링이 내주는 예외 중 최상위 예외인 DataAccessException의 하위 클래스 예외 중 하나가 나올 것이다.
>
> 메소드가 끝날 때까지 예외가 발생하지 않으면 테스트는 실패하게 된다.

**✔ DataAccessException 활용 시 주의사항**

DataAccessException이 기술에 상관없이 어느 정도 추상화된 공통 예외로 변환해주긴 하지만 근본적인 한계 때문에 완벽하다고 기대할 수는 없다. 따라서 사용에 주의를 기울여야 한다.

스프링은 SQLException을 DataAccessException으로 전환하는 다양한 방법을 제공한다. 가장 보편적이고 효과적인 방법은 DB 에러 코드를 이용하는 것이다. SQLException을 코드에서 직접 전환하고 싶다면 SQLExceptionTranslator 인터페이스를 구현한 클래스 중에서 SQLErrorCodeSQLExceptionTranslator를 사용하면 된다.

SQLErrorCodeSQLExceptionTranslator는 에러 코드 변환에 필요한 DB의 종류를 알아내기 위해 현재 연결된 DataSource를 필요로 한다.
```JAVA
public class UserDaoTest {
    @Autowired UserDao dao;
    @Autowired DataSource dataSource;
}
```

DataSource를 사용해 SQLException에서 직접 DuplicateKeyException으로 전환하는 기능을 확인해 보는 학습 테스트를 작성해 보자.
```JAVA
@Test
public void sqlExceptionTranslate() {
    try {
         userDao.add(user1);
         userDao.add(user1);
    }catch(DataAccessException ex) {
         SQLException sqlEx = (SQLException) ex.getRootCause();
         SQLExceptionTranslator set =
                 new SQLErrorCodeSQLExceptionTranslator(this.dataSource);

         DataAccessException translate = set.translate(null, null, sqlEx);
         Assertions.assertEquals(DuplicateKeyException.class, translate.getClass());
    }
}
```
> 스프링 DAO 예외의 최상위에 있는 DataAccessException 클래스로 예외를 잡아서 .getRootCause()를 하면 SQLException를 얻을 수 있다. 위와 같이 SQLErrorCodeSQLExceptionTranslator()를 이용해 해석했을 때 DuplicateKeyException 클래스가 나오는지 확인해보는 클래스를 실행해보면 잘 성공한다.
